Add bookings
CoulthardDC/java-shareit pull request #2
Opened 2023-02-25 12:59 UTC by CoulthardDC

2023-02-26 09:00 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
Оставил пару комментов. Также рекомендую для маппетов юзать mapstruct

2023-02-26 09:00 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                    HttpServletRequest request) {
HttpServletRequest сюда добавлять не надо. Относится ко всем контроллерам.

2023-02-26 09:00 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.info("Получен запрос к эндпоинту: {} {}", request.getMethod(),
так лог лучше не писать, в логи надо написать какие параметры были запрошены, то есть bookerId, bookingDto. Относится ко всем контроллерам.

2023-02-26 09:00 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
предлагаю заюзать mapstruct

2023-02-26 09:00 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return BookingMapper.toBookingDto(bookingRepository.save(booking));
не увидел где вы сеттите статус WAITING

2023-02-26 15:42 UTC, CoulthardDC commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return BookingMapper.toBookingDto(bookingRepository.save(booking));
WAITING сеттится в маппере, когда мапится BookingInputDto в Booking

2023-02-26 15:43 UTC, CoulthardDC commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                    HttpServletRequest request) {
Поправил

2023-02-26 15:44 UTC, CoulthardDC commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
Попробовал) Получилось, но еще почитать про mapstruct нужно)

2023-02-26 15:46 UTC, CoulthardDC commented
WAITING сеттится в маппере, когда мапится BookingInputDto в Booking

2023-02-26 15:57 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return BookingMapper.toBookingDto(bookingRepository.save(booking));
так не надо, маппер пусть занимается только маппингом. 
Сеттьте или в сервисе или в конструкторе.

2023-02-26 15:58 UTC, ErkinKasymaliev requested changes
оставил коммент

2023-02-27 05:40 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-03-12 13:30 UTC, merged