Add item requests
CoulthardDC/java-shareit pull request #3
Opened 2023-03-12 13:30 UTC by CoulthardDC

2023-03-15 21:25 UTC, CoulthardDC commented
Прошу прощения за задержку

2023-03-17 04:28 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-03-17 04:28 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/exception/PermissionException.java
> +package ru.practicum.shareit.item.exception;
этот класс дублируется с тем что в booking. Сделайте вот что: вынесите пакет exception на уровень с booking/item и другими

2023-03-17 04:28 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/request/exception/ItemRequestNotFoundException.java
> +public class ItemRequestNotFoundException extends RuntimeException {
давайте сделаем единные исключение. Не ItemRequestNotFoundException или bookingNotFoundException - а просто NotFoundException. аналогичсно и с другими

2023-03-17 04:28 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    }
в контроллерах еще добавьте verify(repository, time(1)).someRepoMethod() - то есть вы проверите нужное ли кол-во раз вызвался метод из замоканного репозитория

2023-03-17 20:24 UTC, CoulthardDC commented on src/main/java/ru/practicum/shareit/item/exception/PermissionException.java
> +package ru.practicum.shareit.item.exception;
Исправил

2023-03-17 20:24 UTC, CoulthardDC commented on src/main/java/ru/practicum/shareit/request/exception/ItemRequestNotFoundException.java
> +public class ItemRequestNotFoundException extends RuntimeException {
Исправил

2023-03-17 20:27 UTC, CoulthardDC commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    }
Тут возникает сложность: в тестах контроллера я мокаю сервис (т.к. имеются отдельные тесты на сервис) и соответственно не имею доступ к репозиториям. Подумал попытаться в тестах сервиса мокнуть репозиторий (что необходимо для verify), однако там используется репозитории в контексте (с базой H2), и если их мокнуть и положить в контекст, то они будут возвращать null как результат всех методов, и тогда все тесты упадут

2023-03-18 08:26 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    }
хмм, ну хорошо, в целом вашей реализации достаточно

2023-03-18 08:37 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-03-18 11:33 UTC, merged