feat: добавить docker
CoulthardDC/java-shareit pull request #4
Opened 2023-03-21 19:33 UTC by CoulthardDC

2023-03-22 16:37 UTC, ErkinKasymaliev requested changes
привет, отличная работа!
Оставил 1 коммент

2023-03-22 16:37 UTC, ErkinKasymaliev commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<?> create(@Valid @RequestBody ItemDto itemDto,
давайте во всех контроллерах в gateway будет ResponseEntity<Object>

2023-03-23 16:32 UTC, CoulthardDC commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<?> create(@Valid @RequestBody ItemDto itemDto,
Исправил

2023-03-24 11:33 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-03-25 14:50 UTC, merged